apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: tomcat
        image: jayash1845/backend:latest
        ports:
        - containerPort: 8080